## **IMPORTANDO LIBRERÍA NUMPY** ##

In [1]:
import numpy as np

## **CREANDO UNA LISTA DE 10 ELEMENTOS** ##

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## **TRANSFORMANDO LA LISTA EN UN ARRAY** ##

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **COMPROBANDO EL TIPO DE ESTRUCTURA** ##

In [4]:
type(arreglo)

numpy.ndarray

## **CORROBORANDO EL TIPO DE ARREGLO** ##

In [5]:
arreglo.dtype

dtype('int32')

## **DEFINIENDO EL ARRAY DE INT32 A FLOAT32** ##

In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **SIGUE SIENDO UN ARRAY DE INT32** ##


In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **TRANFORMANDO LOS DATOS DE INT32 A FLOAT32** ##

In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **TAMBIEN EXISTE UNA FUNCION SIMILAR AL RANGE PERO OCUPANDO ARRAYS** ##

In [9]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **ARREGLO DE 2 EN 2 UTILIZANDO ARANGE** ##

In [10]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h2 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h2>
<h4 style = "color:aquamarine">OBTENIENDO EL PROMEDIO DEL ARRAY</h3>


In [11]:
promedio = np.mean(arreglo)
promedio

5.5

<h4 style = "color:aquamarine">OBTENIENDO LA MEDIANA DEL ARRAY</h4>


In [12]:
mediana = np.median(arreglo)
mediana

5.5

<h4 style = "color:aquamarine">DESVIACION ESTANDAR DEL ARREGLO</h4>


In [13]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

<h4 style = "color:aquamarine">GENERACION DE UN ARREGLO DE 10 ELEMENTOS DE SOLO UNOS</h4>

In [14]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine">GENERACION DE UN ARREGLO DE 5 ELEMENTOS DE SOLO CEROS</h4>

In [15]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine">TRANFORMANDO EL ARREGLO DE UNOS DE PUNTO FLOTANTE A ENTERO</h4>


In [16]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h2 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h2>
<h4 style = "color:yellow">GENERANDO ARREGLO ALEATORIO DE 5 ELEMENTOS</h4>



In [17]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 

array([0.03914389, 0.14913971, 0.63553588, 0.10371217, 0.68628489,
       0.542255  , 0.08391966, 0.15867195, 0.95120442, 0.71037191])

<h4 style = "color:yellow">GENERANDO UNA MATRIZ ALEATORIA DE 3X3</h4>


In [18]:
matriz = np.random.rand(3,3)
matriz

array([[0.81578957, 0.50765945, 0.65741443],
       [0.52721233, 0.83812251, 0.82866464],
       [0.60585497, 0.11748246, 0.51417247]])

<h4 style = "color:yellow">GENERANDO UN ARREGLO ALEATORIO DE 10 NUMEROS DEL 1 AL 5</h4>


In [19]:
arreglo_aleatorio2  = np.random.randint(1,1001,5)
arreglo_aleatorio2

array([953, 443, 687,   4, 541])

<h4 style = "color:yellow">GENERANDO UNA MATRIZ ALEATORIA DE 10 NUMEROS DEL 1 AL 5</h4>


In [20]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[58, 14, 67, 96,  8, 74, 76, 76, 31, 62],
       [ 7, 17, 66, 39, 92, 72, 20, 24, 27, 67],
       [97, 12, 20, 38,  5, 99, 85, 54, 21,  8],
       [37, 34, 73, 73, 40, 54, 56, 34, 86, 46],
       [ 8, 30, 86, 63, 27, 82, 83, 64, 17, 29],
       [79, 99,  2, 16, 52, 43, 82, 61, 42, 58],
       [22, 90, 16, 81, 59, 61, 60, 42, 16, 67],
       [17, 15, 71, 71, 17, 12, 41,  9, 13, 66],
       [90, 89, 78, 68,  9, 97, 78, 58, 20, 33],
       [77, 13, 73, 71, 66, 54, 65, 75, 50, 62]])