## **Impotando una libreria numpy** ##

In [3]:
## **IMPORTANDO LIBRERIA NUMPY** ## 
import numpy as np

## **Creando una lista de 10 elementos** ## 

In [4]:
lista=list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## **Tranformando la lista a un array** ##

In [5]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Corroborando el tipo de dato** ##

In [9]:
type(arreglo)

numpy.ndarray

## **Corroborando el tipo de datos de arreglo** ##

In [7]:
arreglo.dtype

dtype('int32')

## **Definiendo el array de int32 a float32** ##

In [8]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **Sigue siendo un array de int32** ##

In [10]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Transformando datos int32 a float32** ##

In [11]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

<h1 style = "color=cyan"><b>Algunas funciones de numpy</b></h3>
<h4 style = "colo=aquamarine">obteniendo el promedio del array</h3>

In [12]:
promedio=np.mean(arreglo)
promedio

5.5

In [14]:
mediana=np.median(arreglo)
mediana

5.5

## **DESVIACIÓN ESTANDAR DEL ARREGLO** ##

In [16]:
desviacion_std=np.std(arreglo)
desviacion_std

2.8722813232690143

## **GENERANDO UN ARREGLO DE 10 ELEMENTOS DE SOLO 1'S** ##

In [15]:
arreglo_de_unos=np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## **TRANSFORMANDO ARRAY DE TIPO FLOTANTE A ENTEROS** ##

In [17]:
arreglo_int_ones=arreglo_de_unos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## **CREANDO UN ARREGLO DE 0'S** ##

In [18]:
arreglo_de_cero=np.zeros(10)
arreglo_de_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## **UTILIZANDO LA FUNCION RANDOM** ##
## **GENERANDO VALORES ALEATORIOS DE 5 ELEMENTOS** ##

In [69]:
arreglo_aleatorio= np.random.rand(5)
arreglo_aleatorio

array([0.68531313, 0.54323014, 0.65663071, 0.55488007, 0.19311041])

## **GENERANDO UNA MATRIZ DE 3X3** ##

In [76]:
matriz=np.random.rand(3,3)
matriz

array([[0.24156248, 0.91333708, 0.32708646],
       [0.5810037 , 0.04401962, 0.94064752],
       [0.97610158, 0.32279548, 0.47471069]])

## **GENERANDO UN ARREGLO ALEATORIO DE 10 ELEMENTOS ENTEROS DE 1 AL 5** ##

In [80]:
arreglo_aleatorio2=np.random.randint(1,5,10)
arreglo_aleatorio2

array([2, 1, 2, 1, 2, 4, 1, 4, 1, 4])

## **GENERANDO UNA MATRIZ ALEATORIA DE 10 ELEMENTOS DEL 1 AL 100** ##

In [85]:
matriz2=np.random.randint(1,100,(3,3))
matriz2

array([[95, 60, 63],
       [67, 10, 96],
       [55, 25, 74]])