<h2 style ="color:#00ade4;font-family:Arial">DIMENSIONES</h2>


In [3]:
import numpy as np

<h4 style = "color:cyan">GENERANDO UN ARRAY DE 10 ELEMENTOS CON RANDOM</h4>

In [35]:
arreglo = np.random.randint(1,10,12)
arreglo

array([3, 6, 2, 5, 4, 5, 9, 2, 9, 4, 6, 7])

<h4 style = "color:cyan">OBTENER LA DIMENSION DE UN ARREGLO</h4>

In [39]:
np.shape(arreglo)

(12,)

<h4 style = "color:cyan">TRANSFORMACION DEL VECTOR DE 12 ELEMENTOS A MATRIZ 4X3 CON RESHAPE</h4>

In [56]:
matriz = arreglo.reshape(3,4)
matriz

array([[3, 6, 2, 5],
       [4, 5, 9, 2],
       [9, 4, 6, 7]])

<h4 style = "color:cyan">TRANSFORMACION DEL VECTOR DE 12 ELEMENTOS A MATRIZ DE 4X3 CON RESHAPE</h4>

In [57]:
np.shape(matriz)

(3, 4)

<h4 style = "color:cyan">OTRA TRANSFORMACION DEL VECTOR DE 9 ELEMENTOS A MATRIZ DE 3X4 CON RESHAPE</h4>


In [8]:
matriz = arreglo.reshape(3,4)
matriz

array([[5, 3, 9, 7],
       [2, 9, 2, 1],
       [3, 6, 4, 8]])

<h4 style = "color:cyan">CREANDO UN TENSOR</h4>

In [58]:
t = [[[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]]]
t

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]]]